server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # React SPA
    location / {
        try_files $uri /index.html;
    }

    # API Proxy
    location /auth {
        proxy_pass http://server:5000;
    }

    location /run {
        proxy_pass http://server:5000;
    }

    location /rooms {
        proxy_pass http://server:5000;
    }

    location /room-history {
        proxy_pass http://server:5000;
    }

    location /health {
        proxy_pass http://server:5000;
    }

    # Socket.IO
    location /socket.io/ {
        proxy_pass http://server:5000;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_cache_bypass $http_upgrade;
    }
}